"""empty message

Revision ID: ea970b95c19d
Revises: 9e63d4af6b49
Create Date: 2024-08-28 10:40:47.841808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea970b95c19d'
down_revision = '9e63d4af6b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_peoples', schema=None) as batch_op:
        batch_op.drop_column('fecha_de_favorito')

    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.drop_column('fecha_de_favorito')

    with op.batch_alter_table('favoritos_vehicles', schema=None) as batch_op:
        batch_op.drop_column('fecha_de_favorito')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('people_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld_id'], ['id'])
        batch_op.drop_column('homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_homeworld_fkey', 'planet', ['homeworld'], ['id'])
        batch_op.drop_column('homeworld_id')

    with op.batch_alter_table('favoritos_vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_favorito', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('favoritos_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_favorito', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('favoritos_peoples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_favorito', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
